apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-backend
  labels:
    app: student-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-backend
  template:
    metadata:
      labels:
        app: student-backend
    spec:
      containers:
        - name: backend
          image: student-backend:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "256m"
              memory: "512Mi"
            limits:
              cpu: "512m"
              memory: "1024Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: student-backend
  labels:
    app: student-backend
spec:
  type: ClusterIP
  selector:
    app: student-backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
